services:
  - type: web
    name: zyraa-web
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_XDtgskY6eK8w@ep-steep-meadow-ahw3njh6-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require"
      - key: CLOUDINARY_CLOUD_NAME
        value: "dg04dd5o1"
      - key: CLOUDINARY_API_KEY
        value: "243896825183337"
      - key: CLOUDINARY_API_SECRET
        value: "JgyFPK4aQ7qkNNWWqA6Dqmitx3M"
