# Generated by Django 5.2.4 on 2026-06-14 18:42

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='posts/videos/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='music',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='stories/music/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='stories/videos/'),
        ),
    ]
